// packages/vue/src/Alert.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls, type ColorScheme } from './types';

const props = withDefaults(defineProps<{
  variant?: ColorScheme;
  dismissible?: boolean;
}>(), { variant: 'info', dismissible: false });

const emit = defineEmits<{ dismiss: [] }>();

const className = computed(() => cls('av-alert', `av-alert-${props.variant}`));
</script>

<template>
  <div :class="className" role="alert">
    <slot name="icon" />
    <div class="av-alert-body">
      <div v-if="$slots.title" class="av-alert-title"><slot name="title" /></div>
      <div class="av-alert-message"><slot /></div>
    </div>
    <button v-if="dismissible" type="button" class="av-alert-dismiss" aria-label="Dismiss" @click="emit('dismiss')">
      &times;
    </button>
  </div>
</template>

// packages/react/src/Alert.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { cls, type ColorScheme } from './types';

export interface AlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  /** Color variant. Defaults to `'info'`. */
  variant?: ColorScheme;
  /** Optional title rendered above the message. */
  title?: ReactNode;
  /** Whether the alert can be dismissed (renders an × button). */
  dismissible?: boolean;
  /** Called when the dismiss button is clicked. */
  onDismiss?: () => void;
  /** Icon rendered on the left side. */
  icon?: ReactNode;
}

export function Alert({
  variant = 'info',
  title,
  dismissible = false,
  onDismiss,
  icon,
  className = '',
  children,
  ...props
}: AlertProps) {
  const computed = cls('av-alert', `av-alert-${variant}`, className);

  return (
    <div className={computed} role="alert" {...props}>
      {icon && <span className="av-alert-icon">{icon}</span>}
      <div className="av-alert-body">
        {title && <div className="av-alert-title">{title}</div>}
        {children && <div className="av-alert-message">{children}</div>}
      </div>
      {dismissible && (
        <button
          type="button"
          className="av-alert-dismiss"
          aria-label="Dismiss"
          onClick={onDismiss}
        >
          &times;
        </button>
      )}
    </div>
  );
}
