// packages/vue/src/Box.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import { cls } from './types';

const props = withDefaults(defineProps<{
  as?: string;
  display?: CSSProperties['display'];
  direction?: CSSProperties['flexDirection'];
  align?: CSSProperties['alignItems'];
  justify?: CSSProperties['justifyContent'];
  gap?: CSSProperties['gap'];
  p?: CSSProperties['padding'];
  px?: CSSProperties['padding'];
  py?: CSSProperties['padding'];
  m?: CSSProperties['margin'];
  w?: CSSProperties['width'];
  h?: CSSProperties['height'];
  overflow?: CSSProperties['overflow'];
  position?: CSSProperties['position'];
  radius?: CSSProperties['borderRadius'];
  bg?: CSSProperties['background'];
}>(), {
  as: 'div',
});

const inlineStyle = computed<CSSProperties>(() => ({
  ...(props.display ? { display: props.display } : {}),
  ...(props.direction ? { flexDirection: props.direction } : {}),
  ...(props.align ? { alignItems: props.align } : {}),
  ...(props.justify ? { justifyContent: props.justify } : {}),
  ...(props.gap ? { gap: props.gap } : {}),
  ...(props.p ? { padding: props.p } : {}),
  ...(props.px ? { paddingLeft: props.px, paddingRight: props.px } : {}),
  ...(props.py ? { paddingTop: props.py, paddingBottom: props.py } : {}),
  ...(props.m ? { margin: props.m } : {}),
  ...(props.w ? { width: props.w } : {}),
  ...(props.h ? { height: props.h } : {}),
  ...(props.overflow ? { overflow: props.overflow } : {}),
  ...(props.position ? { position: props.position } : {}),
  ...(props.radius ? { borderRadius: props.radius } : {}),
  ...(props.bg ? { background: props.bg } : {}),
}));
</script>

<template>
  <component :is="as" :class="cls('av-box')" :style="inlineStyle">
    <slot />
  </component>
</template>

// packages/react/src/Box.tsx
import type { CSSProperties, ElementType, HTMLAttributes } from 'react';
import { cls } from './types';

export interface BoxProps extends HTMLAttributes<HTMLElement> {
  /** Rendered element. Defaults to `'div'`. */
  as?: ElementType;
  /** display shorthand. */
  display?: CSSProperties['display'];
  /** flexDirection shorthand. */
  direction?: CSSProperties['flexDirection'];
  /** alignItems shorthand. */
  align?: CSSProperties['alignItems'];
  /** justifyContent shorthand. */
  justify?: CSSProperties['justifyContent'];
  /** gap shorthand. */
  gap?: CSSProperties['gap'];
  /** padding shorthand. */
  p?: CSSProperties['padding'];
  /** paddingX shorthand. */
  px?: CSSProperties['padding'];
  /** paddingY shorthand. */
  py?: CSSProperties['padding'];
  /** margin shorthand. */
  m?: CSSProperties['margin'];
  /** width shorthand. */
  w?: CSSProperties['width'];
  /** height shorthand. */
  h?: CSSProperties['height'];
  /** overflow shorthand. */
  overflow?: CSSProperties['overflow'];
  /** position shorthand. */
  position?: CSSProperties['position'];
  /** borderRadius shorthand. */
  radius?: CSSProperties['borderRadius'];
  /** background shorthand. */
  bg?: CSSProperties['background'];
}

export function Box({
  as: Tag = 'div',
  display,
  direction,
  align,
  justify,
  gap,
  p,
  px,
  py,
  m,
  w,
  h,
  overflow,
  position,
  radius,
  bg,
  className = '',
  style,
  children,
  ...props
}: BoxProps) {
  const inlineStyle: CSSProperties = {
    ...(display ? { display } : {}),
    ...(direction ? { flexDirection: direction } : {}),
    ...(align ? { alignItems: align } : {}),
    ...(justify ? { justifyContent: justify } : {}),
    ...(gap ? { gap } : {}),
    ...(p ? { padding: p } : {}),
    ...(px ? { paddingLeft: px, paddingRight: px } : {}),
    ...(py ? { paddingTop: py, paddingBottom: py } : {}),
    ...(m ? { margin: m } : {}),
    ...(w ? { width: w } : {}),
    ...(h ? { height: h } : {}),
    ...(overflow ? { overflow } : {}),
    ...(position ? { position } : {}),
    ...(radius ? { borderRadius: radius } : {}),
    ...(bg ? { background: bg } : {}),
    ...style,
  };

  return (
    <Tag className={cls('av-box', className)} style={inlineStyle} {...props}>
      {children}
    </Tag>
  );
}
