// packages/vue/src/ButtonGroup.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls, type Size } from './types';

const props = withDefaults(defineProps<{
  size?: Size;
  vertical?: boolean;
  fluid?: boolean;
}>(), {
  vertical: false,
  fluid: false,
});

const className = computed(() =>
  cls(
    'av-btn-group',
    props.vertical && 'av-btn-group-vertical',
    props.fluid && 'av-btn-group-fluid',
    props.size && `av-btn-group-${props.size}`
  )
);
</script>

<template>
  <div role="group" :class="className">
    <slot />
  </div>
</template>

// packages/react/src/ButtonGroup.tsx
import type { HTMLAttributes } from 'react';
import { cls, type Size } from './types';

export interface ButtonGroupProps extends HTMLAttributes<HTMLDivElement> {
  /** Size applied to all buttons. */
  size?: Size;
  /** Vertical layout. */
  vertical?: boolean;
  /** Stretch to fill container. */
  fluid?: boolean;
}

export function ButtonGroup({ size, vertical = false, fluid = false, className = '', children, ...props }: ButtonGroupProps) {
  return (
    <div
      role="group"
      className={cls(
        'av-btn-group',
        vertical && 'av-btn-group-vertical',
        fluid && 'av-btn-group-fluid',
        size && `av-btn-group-${size}`,
        className,
      )}
      {...props}
    >
      {children}
    </div>
  );
}
