// packages/vue/src/EmptyState.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

const props = withDefaults(defineProps<{
  title: string;
  description?: string;
  size?: 'sm' | 'md' | 'lg';
}>(), { size: 'md' });

const className = computed(() => cls('av-empty-state', props.size !== 'md' && `av-empty-state-${props.size}`));
</script>

<template>
  <div :class="className" role="status">
    <div v-if="$slots.illustration" class="av-empty-state-illustration"><slot name="illustration" /></div>
    <div class="av-empty-state-title">{{ title }}</div>
    <div v-if="description" class="av-empty-state-description">{{ description }}</div>
    <div v-if="$slots.action" class="av-empty-state-actions"><slot name="action" /></div>
  </div>
</template>

// packages/react/src/EmptyState.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { cls } from './types';

export interface EmptyStateProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  /** Illustration or icon. */
  illustration?: ReactNode;
  /** Main title. */
  title: ReactNode;
  /** Descriptive text. */
  description?: ReactNode;
  /** Primary action button/link. */
  action?: ReactNode;
  /** Secondary action. */
  secondaryAction?: ReactNode;
  /** Size variant. Defaults to `'md'`. */
  size?: 'sm' | 'md' | 'lg';
}

export function EmptyState({
  illustration,
  title,
  description,
  action,
  secondaryAction,
  size = 'md',
  className = '',
  ...props
}: EmptyStateProps) {
  return (
    <div
      className={cls('av-empty-state', size !== 'md' && `av-empty-state-${size}`, className)}
      role="status"
      {...props}
    >
      {illustration && <div className="av-empty-state-illustration">{illustration}</div>}
      <div className="av-empty-state-title">{title}</div>
      {description && <div className="av-empty-state-description">{description}</div>}
      {(action || secondaryAction) && (
        <div className="av-empty-state-actions">
          {action}
          {secondaryAction}
        </div>
      )}
    </div>
  );
}
