// packages/vue/src/SearchInput.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { cls, type Size } from './types';

const props = withDefaults(defineProps<{
  modelValue?: string;
  label?: string;
  size?: Size;
  fullWidth?: boolean;
  debounce?: number;
  clearable?: boolean;
  loading?: boolean;
  id?: string;
}>(), {
  size: 'md',
  fullWidth: false,
  debounce: 0,
  clearable: true,
  loading: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
  'search': [value: string];
  'input': [e: Event];
}>();

const uid = computed(() => props.id ?? `sch-${Math.random().toString(36).slice(2, 7)}`);
const internal = ref('');
const displayValue = computed(() => props.modelValue ?? internal.value);

const inputRef = ref<HTMLInputElement | null>(null);

let timer: ReturnType<typeof setTimeout> | null = null;

const onInput = (e: Event) => {
  const val = (e.target as HTMLInputElement).value;
  internal.value = val;
  emit('update:modelValue', val);
  emit('input', e);
  
  if (timer) clearTimeout(timer);
  if (props.debounce > 0) {
    timer = setTimeout(() => emit('search', val), props.debounce);
  } else {
    emit('search', val);
  }
};

const clear = () => {
  internal.value = '';
  emit('update:modelValue', '');
  emit('search', '');
  if (inputRef.value) {
    inputRef.value.value = '';
    inputRef.value.focus();
  }
};
</script>

<template>
  <div :class="cls('av-search-input', fullWidth && 'av-search-input-full')">
    <label v-if="label" :for="uid" class="av-form-label">{{ label }}</label>
    
    <div :class="cls('av-input-wrapper av-input-wrapper-start', displayValue && clearable && 'av-input-wrapper-end')">
      <span class="av-input-adornment av-input-adornment-start" aria-hidden="true">
        <span v-if="loading" class="av-spinner av-spinner-border av-spinner-sm av-spinner-primary" role="status" aria-label="Searching" />
        <span v-else class="av-search-icon">🔍</span>
      </span>
      
      <input
        ref="inputRef"
        :id="uid"
        type="search"
        :class="cls('av-input', size !== 'md' && `av-input-${size}`)"
        :value="displayValue"
        autocomplete="off"
        @input="onInput"
      />
      
      <span v-if="clearable && displayValue" class="av-input-adornment av-input-adornment-end">
        <button type="button" class="av-search-clear" aria-label="Clear search" @click="clear">
          &times;
        </button>
      </span>
    </div>
  </div>
</template>

// packages/react/src/SearchInput.tsx
import { forwardRef, useState, useRef, useId, type ChangeEvent, type InputHTMLAttributes } from 'react';
import { cls, type Size } from './types';

export interface SearchInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label?: string;
  size?: Size;
  fullWidth?: boolean;
  /** Debounce delay in ms. 0 = no debounce. Defaults to 0. */
  debounce?: number;
  /** Called with the search value (debounced if set). */
  onSearch?: (value: string) => void;
  /** Show clear button when input has value. */
  clearable?: boolean;
  /** Loading state (shows spinner). */
  loading?: boolean;
}

export const SearchInput = forwardRef<HTMLInputElement, SearchInputProps>(function SearchInput(
  {
    label,
    size = 'md',
    fullWidth = false,
    debounce = 0,
    onSearch,
    clearable = true,
    loading = false,
    className = '',
    id,
    value: controlledValue,
    defaultValue = '',
    onChange,
    ...props
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const [internal, setInternal] = useState(String(defaultValue));
  const timer = useRef<ReturnType<typeof setTimeout>>();

  const displayValue = controlledValue !== undefined ? String(controlledValue) : internal;

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    const val = e.target.value;
    setInternal(val);
    onChange?.(e);

    if (onSearch) {
      clearTimeout(timer.current);
      if (debounce > 0) {
        timer.current = setTimeout(() => onSearch(val), debounce);
      } else {
        onSearch(val);
      }
    }
  }

  function clear() {
    setInternal('');
    onSearch?.('');
    if (ref && 'current' in ref && ref.current) {
      ref.current.value = '';
      ref.current.focus();
    }
  }

  return (
    <div className={cls('av-search-input', fullWidth && 'av-search-input-full', className)}>
      {label && <label htmlFor={inputId} className="av-form-label">{label}</label>}
      <div className={cls('av-input-wrapper av-input-wrapper-start', displayValue && clearable && 'av-input-wrapper-end')}>
        <span className="av-input-adornment av-input-adornment-start" aria-hidden="true">
          {loading
            ? <span className="av-spinner av-spinner-border av-spinner-sm av-spinner-primary" role="status" aria-label="Searching" />
            : <span className="av-search-icon">🔍</span>
          }
        </span>
        <input
          ref={ref}
          id={inputId}
          type="search"
          className={cls('av-input', size !== 'md' && `av-input-${size}`)}
          value={displayValue}
          onChange={handleChange}
          autoComplete="off"
          {...props}
        />
        {clearable && displayValue && (
          <span className="av-input-adornment av-input-adornment-end">
            <button type="button" className="av-search-clear" aria-label="Clear search" onClick={clear}>&times;</button>
          </span>
        )}
      </div>
    </div>
  );
});
SearchInput.displayName = 'SearchInput';
