// packages/vue/src/Section.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

const props = withDefaults(defineProps<{
  size?: 'sm' | 'md' | 'lg' | 'xl';
  fullWidth?: boolean;
}>(), {
  size: 'md',
  fullWidth: false,
});

const className = computed(() =>
  cls(
    'av-section',
    `av-section-${props.size}`,
    props.fullWidth && 'av-section-full',
  )
);
</script>

<template>
  <section :class="className">
    <slot />
  </section>
</template>

// packages/react/src/Section.tsx
import type { HTMLAttributes } from 'react';
import { cls } from './types';

export interface SectionProps extends HTMLAttributes<HTMLElement> {
  /** Vertical padding size. Defaults to `'md'`. */
  size?: 'sm' | 'md' | 'lg' | 'xl';
  /** Use full-width background. */
  fullWidth?: boolean;
}

export function Section({ size = 'md', fullWidth = false, className = '', children, ...props }: SectionProps) {
  return (
    <section
      className={cls('av-section', `av-section-${size}`, fullWidth && 'av-section-full', className)}
      {...props}
    >
      {children}
    </section>
  );
}
