// packages/vue/src/Spinner.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls, type ColorScheme, type Size } from './types';

const props = withDefaults(defineProps<{
  variant?: 'border' | 'dots' | 'grow';
  color?: ColorScheme;
  size?: Size;
  label?: string;
}>(), { variant: 'border', color: 'primary', size: 'md', label: 'Loading…' });

const className = computed(() =>
  cls('av-spinner', `av-spinner-${props.variant}`, `av-spinner-${props.color}`, props.size !== 'md' && `av-spinner-${props.size}`)
);
</script>

<template>
  <span :class="className" role="status" :aria-label="label">
    <span class="av-sr-only">{{ label }}</span>
  </span>
</template>

// packages/react/src/Spinner.tsx
import type { HTMLAttributes } from 'react';
import { cls, type ColorScheme, type Size } from './types';

export interface SpinnerProps extends HTMLAttributes<HTMLSpanElement> {
  /** Visual variant. Defaults to `'border'`. */
  variant?: 'border' | 'dots' | 'grow';
  /** Color. Defaults to `'primary'`. */
  color?: ColorScheme;
  /** Size modifier. Defaults to `'md'`. */
  size?: Size;
  /** Accessible label. Defaults to `'Loading…'`. */
  label?: string;
}

export function Spinner({
  variant = 'border',
  color = 'primary',
  size = 'md',
  label = 'Loading…',
  className = '',
  ...props
}: SpinnerProps) {
  return (
    <span
      className={cls(
        'av-spinner',
        `av-spinner-${variant}`,
        `av-spinner-${color}`,
        size !== 'md' && `av-spinner-${size}`,
        className,
      )}
      role="status"
      aria-label={label}
      {...props}
    >
      <span className="av-sr-only">{label}</span>
    </span>
  );
}
