// packages/vue/src/SplitPane.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

const props = withDefaults(defineProps<{
  vertical?: boolean;
}>(), {
  vertical: false,
});

const className = computed(() =>
  cls(
    'av-split-pane',
    props.vertical && 'av-split-pane--vertical'
  )
);
</script>

<template>
  <div :class="className">
    <slot />
  </div>
</template>

// packages/react/src/SplitPane.tsx
import type { HTMLAttributes } from 'react';
import { cls } from './types';

export interface SplitPaneProps extends HTMLAttributes<HTMLDivElement> {
  vertical?: boolean;
}
export function SplitPane({ className = '', vertical, children, ...props }: SplitPaneProps) {
  return (
    <div className={cls('av-split-pane', vertical && 'av-split-pane--vertical', className)} {...props}>
      {children}
    </div>
  );
}

export interface SplitPanePaneProps extends HTMLAttributes<HTMLDivElement> {}
export function SplitPanePane({ className = '', children, ...props }: SplitPanePaneProps) {
  return (
    <div className={cls('av-split-pane__pane', className)} {...props}>
      {children}
    </div>
  );
}

export interface SplitPaneResizerProps extends HTMLAttributes<HTMLDivElement> {}
export function SplitPaneResizer({ className = '', ...props }: SplitPaneResizerProps) {
  return <div className={cls('av-split-pane__resizer', className)} {...props} />;
}
