// packages/vue/src/Stepper.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

export interface StepItem {
  label: string;
  description?: string;
}

const props = withDefaults(defineProps<{
  steps: StepItem[];
  activeStep: number;
  orientation?: 'horizontal' | 'vertical';
  showCompleted?: boolean;
}>(), { orientation: 'horizontal', showCompleted: true });

const wrapperClass = computed(() => cls('av-stepper', `av-stepper-${props.orientation}`));
</script>

<template>
  <div :class="wrapperClass" aria-label="Progress steps">
    <div
      v-for="(step, i) in steps"
      :key="i"
      :class="cls('av-step', i < activeStep && 'av-step-completed', i === activeStep && 'av-step-active')"
      :aria-current="i === activeStep ? 'step' : undefined"
    >
      <div class="av-step-indicator">
        <span v-if="i < activeStep && showCompleted" class="av-step-check" aria-label="Completed">✓</span>
        <slot v-else :name="`icon-${i}`">
          <span class="av-step-number">{{ i + 1 }}</span>
        </slot>
      </div>
      <div class="av-step-content">
        <div class="av-step-label">{{ step.label }}</div>
        <div v-if="step.description" class="av-step-description">{{ step.description }}</div>
      </div>
      <div v-if="i < steps.length - 1" class="av-step-connector" aria-hidden="true" />
    </div>
  </div>
</template>

// packages/react/src/Stepper.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { cls } from './types';

export interface StepItem {
  /** Step label. */
  label: ReactNode;
  /** Optional description. */
  description?: ReactNode;
  /** Optional icon. Overrides default step number. */
  icon?: ReactNode;
}

export interface StepperProps extends HTMLAttributes<HTMLDivElement> {
  /** Step definitions. */
  steps: StepItem[];
  /** Active step index (0-indexed). */
  activeStep: number;
  /** Orientation. Defaults to `'horizontal'`. */
  orientation?: 'horizontal' | 'vertical';
  /** Show check icon for completed steps. */
  showCompleted?: boolean;
}

export function Stepper({
  steps,
  activeStep,
  orientation = 'horizontal',
  showCompleted = true,
  className = '',
  ...props
}: StepperProps) {
  return (
    <div
      className={cls('av-stepper', `av-stepper-${orientation}`, className)}
      aria-label="Progress steps"
      {...props}
    >
      {steps.map((step, i) => {
        const completed = i < activeStep;
        const active = i === activeStep;
        return (
          <div
            key={i}
            className={cls(
              'av-step',
              completed && 'av-step-completed',
              active && 'av-step-active',
            )}
            aria-current={active ? 'step' : undefined}
          >
            <div className="av-step-indicator">
              {completed && showCompleted ? (
                <span className="av-step-check" aria-label="Completed">✓</span>
              ) : (
                step.icon ?? <span className="av-step-number">{i + 1}</span>
              )}
            </div>
            <div className="av-step-content">
              <div className="av-step-label">{step.label}</div>
              {step.description && <div className="av-step-description">{step.description}</div>}
            </div>
            {i < steps.length - 1 && <div className="av-step-connector" aria-hidden="true" />}
          </div>
        );
      })}
    </div>
  );
}
