// packages/vue/src/ThemeToggle.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { cls } from './types';

type Theme = 'light' | 'dark' | 'forest' | 'ocean' | 'professional' | 'corporate';
const ICONS: Record<string, string> = { light: '☀️', dark: '🌙', forest: '🌲', ocean: '🌊', professional: '💼', corporate: '🏢' };

const props = withDefaults(defineProps<{
  themes?: Theme[];
  modelValue?: Theme;
  defaultTheme?: Theme;
  showLabel?: boolean;
}>(), {
  themes: () => ['light', 'dark'] as Theme[],
  defaultTheme: 'light',
  showLabel: false,
});

const emit = defineEmits<{ 'update:modelValue': [theme: Theme] }>();

const internal = ref<Theme>(props.modelValue ?? props.defaultTheme);
const current = computed(() => props.modelValue ?? internal.value);

watch(current, (theme) => {
  document.documentElement.setAttribute('data-av-theme', theme);
}, { immediate: true });

function cycle() {
  const idx = props.themes.indexOf(current.value);
  const next = props.themes[(idx + 1) % props.themes.length];
  internal.value = next;
  emit('update:modelValue', next);
}
</script>

<template>
  <button
    type="button"
    :class="cls('av-theme-toggle', `av-theme-toggle-${current}`)"
    :aria-label="`Switch theme (current: ${current})`"
    @click="cycle"
  >
    <span aria-hidden="true">{{ ICONS[current] ?? '🎨' }}</span>
    <span v-if="showLabel" class="av-theme-toggle-label">{{ current }}</span>
  </button>
</template>

// packages/react/src/ThemeToggle.tsx
import { useState, useEffect, type ButtonHTMLAttributes } from 'react';
import { cls } from './types';

export type Theme = 'light' | 'dark' | 'forest' | 'ocean' | 'professional' | 'corporate';

const THEMES: Theme[] = ['light', 'dark', 'forest', 'ocean', 'professional', 'corporate'];

export interface ThemeToggleProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Which themes to cycle through. Defaults to `['light', 'dark']`. */
  themes?: Theme[];
  /** Initial theme. */
  defaultTheme?: Theme;
  /** Controlled theme. */
  theme?: Theme;
  /** Called when theme changes. */
  onThemeChange?: (theme: Theme) => void;
  /** Show theme label. */
  showLabel?: boolean;
}

export function ThemeToggle({
  themes = ['light', 'dark'],
  defaultTheme = 'light',
  theme: controlledTheme,
  onThemeChange,
  showLabel = false,
  className = '',
  ...props
}: ThemeToggleProps) {
  const [internal, setInternal] = useState<Theme>(() => {
    if (typeof document === 'undefined') return defaultTheme;
    return (document.documentElement.getAttribute('data-av-theme') as Theme) ?? defaultTheme;
  });

  const current = controlledTheme ?? internal;

  useEffect(() => {
    document.documentElement.setAttribute('data-av-theme', current);
  }, [current]);

  function cycle() {
    const idx = themes.indexOf(current);
    const next = themes[(idx + 1) % themes.length];
    setInternal(next);
    onThemeChange?.(next);
  }

  const ICONS: Record<string, string> = { light: '☀️', dark: '🌙', forest: '🌲', ocean: '🌊', professional: '💼', corporate: '🏢' };

  return (
    <button
      type="button"
      className={cls('av-theme-toggle', `av-theme-toggle-${current}`, className)}
      onClick={cycle}
      aria-label={`Switch theme (current: ${current})`}
      {...props}
    >
      <span aria-hidden="true">{ICONS[current] ?? '🎨'}</span>
      {showLabel && <span className="av-theme-toggle-label">{current}</span>}
    </button>
  );
}

export { THEMES };
