// packages/vue/src/Tooltip.vue
<script setup lang="ts">
import { ref } from 'vue';
import { cls, type Placement } from './types';

const props = withDefaults(defineProps<{
  content: string;
  placement?: Placement;
  delay?: number;
  disabled?: boolean;
}>(), { placement: 'top', delay: 200, disabled: false });

const visible = ref(false);
let timer: ReturnType<typeof setTimeout>;

function show() {
  if (props.disabled) return;
  timer = setTimeout(() => { visible.value = true; }, props.delay);
}
function hide() {
  clearTimeout(timer);
  visible.value = false;
}
</script>

<template>
  <span class="av-tooltip-wrapper" @mouseenter="show" @mouseleave="hide" @focus="show" @blur="hide">
    <slot />
    <span v-if="visible" role="tooltip" :class="cls('av-tooltip', `av-tooltip-${placement}`)">
      {{ content }}
    </span>
  </span>
</template>

// packages/react/src/Tooltip.tsx
import { useState, useRef, type HTMLAttributes, type ReactNode } from 'react';
import { cls, type Placement } from './types';

export interface TooltipProps extends Omit<HTMLAttributes<HTMLSpanElement>, 'content'> {
  /** Tooltip text/content. */
  content: ReactNode;
  /** Placement relative to trigger. Defaults to `'top'`. */
  placement?: Placement;
  /** Delay before showing (ms). Defaults to 200. */
  delay?: number;
  /** Disable the tooltip. */
  disabled?: boolean;
}

export function Tooltip({
  content,
  placement = 'top',
  delay = 200,
  disabled = false,
  className = '',
  children,
  ...props
}: TooltipProps) {
  const [visible, setVisible] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout>>();

  function show() {
    if (disabled) return;
    timer.current = setTimeout(() => setVisible(true), delay);
  }

  function hide() {
    clearTimeout(timer.current);
    setVisible(false);
  }

  return (
    <span
      className={cls('av-tooltip-wrapper', className)}
      onMouseEnter={show}
      onMouseLeave={hide}
      onFocus={show}
      onBlur={hide}
      {...props}
    >
      {children}
      {visible && (
        <span
          role="tooltip"
          className={cls('av-tooltip', `av-tooltip-${placement}`)}
        >
          {content}
        </span>
      )}
    </span>
  );
}
