// packages/react/src/Divider.tsx
import type { HTMLAttributes } from 'react';
import { cls } from './types';

export interface DividerProps extends HTMLAttributes<HTMLHRElement> {
  /** Vertical divider (for use inside flex rows). */
  vertical?: boolean;
  /** Label in the middle. */
  label?: string;
  /** Color variant. */
  variant?: 'solid' | 'dashed' | 'dotted';
}

export function Divider({ vertical = false, label, variant = 'solid', className = '', ...props }: DividerProps) {
  if (label) {
    return (
      <div className={cls('av-divider', 'av-divider-labeled', className)}>
        <span className="av-divider-label">{label}</span>
      </div>
    );
  }
  return (
    <hr
      className={cls(
        'av-divider',
        vertical && 'av-divider-vertical',
        variant !== 'solid' && `av-divider-${variant}`,
        className,
      )}
      aria-hidden="true"
      {...props}
    />
  );
}

// packages/vue/src/Divider.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

const props = withDefaults(defineProps<{
  vertical?: boolean;
  label?: string;
  variant?: 'solid' | 'dashed' | 'dotted';
}>(), {
  vertical: false,
  variant: 'solid',
});

const isLabeled = computed(() => !!props.label);

const className = computed(() =>
  cls(
    'av-divider',
    props.vertical && 'av-divider-vertical',
    props.variant !== 'solid' && `av-divider-${props.variant}`,
  )
);
</script>

<template>
  <div v-if="isLabeled" :class="cls('av-divider', 'av-divider-labeled')">
    <span class="av-divider-label">{{ label }}</span>
  </div>
  <hr
    v-else
    :class="className"
    aria-hidden="true"
  />
</template>
