// packages/react/src/InputGroup.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { cls } from './types';

export interface InputGroupProps extends HTMLAttributes<HTMLDivElement> {
  /** Content prepended before the input. */
  prepend?: ReactNode;
  /** Content appended after the input. */
  append?: ReactNode;
  /** Makes the group fill its container. */
  fluid?: boolean;
}

export function InputGroup({ prepend, append, fluid, className = '', children, ...props }: InputGroupProps) {
  return (
    <div className={cls('av-input-group', fluid && 'av-input-group-fluid', className)} {...props}>
      {prepend && <span className="av-input-group-text">{prepend}</span>}
      {children}
      {append && <span className="av-input-group-text">{append}</span>}
    </div>
  );
}

export interface InputGroupTextProps extends HTMLAttributes<HTMLSpanElement> {}
export function InputGroupText({ className = '', children, ...props }: InputGroupTextProps) {
  return (
    <span className={cls('av-input-group-text', className)} {...props}>
      {children}
    </span>
  );
}

// packages/vue/src/InputGroup.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

const props = defineProps<{
  fluid?: boolean;
}>();

const className = computed(() =>
  cls(
    'av-input-group',
    props.fluid && 'av-input-group-fluid'
  )
);
</script>

<template>
  <div :class="className">
    <span v-if="$slots.prepend" class="av-input-group-text">
      <slot name="prepend" />
    </span>
    <slot />
    <span v-if="$slots.append" class="av-input-group-text">
      <slot name="append" />
    </span>
  </div>
</template>
