// packages/react/src/Modal.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { cls, type Size } from './types';
import { useFocusTrap } from './hooks/useFocusTrap';
import type React from 'react';

export interface ModalProps {
  open: boolean;
  onClose: () => void;
  title?: ReactNode;
  footer?: ReactNode;
  size?: Size;
  staticBackdrop?: boolean;
  hideCloseButton?: boolean;
  className?: string;
  children?: ReactNode;
  'aria-label'?: string;
  /** Transition duration in ms. Defaults to 200. */
  transitionDuration?: number;
}

export function Modal({
  open,
  onClose,
  title,
  footer,
  size = 'md',
  staticBackdrop = false,
  hideCloseButton = false,
  className = '',
  children,
  'aria-label': ariaLabel,
  transitionDuration = 200,
}: ModalProps) {
  // `mounted` keeps the DOM node alive during exit transition
  const [mounted, setMounted] = useState(open);
  // `visible` drives the CSS entering/leaving class
  const [visible, setVisible] = useState(false);

  const trapRef = useFocusTrap<HTMLDivElement>(open);

  useEffect(() => {
    if (open) {
      setMounted(true);
      // next tick so the entering class applies after mount
      const raf = requestAnimationFrame(() => setVisible(true));
      return () => cancelAnimationFrame(raf);
    } else {
      setVisible(false);
      const t = setTimeout(() => setMounted(false), transitionDuration);
      return () => clearTimeout(t);
    }
  }, [open, transitionDuration]);

  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !staticBackdrop) onClose();
    };
    document.addEventListener('keydown', handleKey);
    return () => {
      document.removeEventListener('keydown', handleKey);
      document.body.style.overflow = prev;
    };
  }, [open, onClose, staticBackdrop]);

  if (!mounted) return null;

  const titleId = title ? 'av-modal-title' : undefined;

  return createPortal(
    <div
      className={cls('av-modal-backdrop', visible && 'av-modal-backdrop-show')}
      onClick={(e) => { if (!staticBackdrop && e.target === e.currentTarget) onClose(); }}
      role="presentation"
    >
      <div
        ref={trapRef}
        className={cls(
          'av-modal-dialog',
          size !== 'md' && `av-modal-${size}`,
          visible && 'av-modal-open',
          className,
        )}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-label={!title ? ariaLabel : undefined}
      >
        {title && (
          <div className="av-modal-header">
            <h5 className="av-modal-title" id="av-modal-title">{title}</h5>
            {!hideCloseButton && (
              <button type="button" className="av-modal-close" aria-label="Close modal" onClick={onClose}>
                &times;
              </button>
            )}
          </div>
        )}
        <div className="av-modal-body">{children}</div>
        {footer && <div className="av-modal-footer">{footer}</div>}
      </div>
    </div>,
    document.body,
  );
}

// packages/vue/src/Modal.vue
<script setup lang="ts">
import { watch, onUnmounted, computed } from 'vue';
import { cls, type Size } from './types';

const props = withDefaults(defineProps<{
  open: boolean;
  size?: Size;
  staticBackdrop?: boolean;
}>(), { size: 'md', staticBackdrop: false });

const emit = defineEmits<{ close: [] }>();

function handleKey(e: KeyboardEvent) {
  if (e.key === 'Escape' && !props.staticBackdrop) emit('close');
}

watch(() => props.open, (v) => {
  if (v) {
    document.body.style.overflow = 'hidden';
    document.addEventListener('keydown', handleKey);
  } else {
    document.body.style.overflow = '';
    document.removeEventListener('keydown', handleKey);
  }
});

onUnmounted(() => {
  document.body.style.overflow = '';
  document.removeEventListener('keydown', handleKey);
});

function handleBackdrop(e: MouseEvent) {
  if (!props.staticBackdrop && (e.target as HTMLElement).classList.contains('av-modal-backdrop-show')) {
    emit('close');
  }
}

const dialogClass = computed(() => cls('av-modal-dialog', props.size !== 'md' && `av-modal-${props.size}`));
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      class="av-modal-backdrop av-modal-backdrop-show"
      role="presentation"
      @click="handleBackdrop"
    >
      <div :class="dialogClass" role="dialog" aria-modal="true">
        <div v-if="$slots.title" class="av-modal-header">
          <h5 class="av-modal-title"><slot name="title" /></h5>
          <button type="button" class="av-modal-close" aria-label="Close" @click="emit('close')">&times;</button>
        </div>
        <div class="av-modal-body"><slot /></div>
        <div v-if="$slots.footer" class="av-modal-footer"><slot name="footer" /></div>
      </div>
    </div>
  </Teleport>
</template>
