// packages/react/src/NumberInput.tsx
import { forwardRef, useRef, useState, useId, type ChangeEvent, type InputHTMLAttributes } from 'react';
import { cls, type Size } from './types';

export interface NumberInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size' | 'onChange' | 'value' | 'defaultValue'> {
  label?: string;
  helperText?: string;
  error?: string;
  size?: Size;
  fullWidth?: boolean;
  /** Step amount. Defaults to 1. */
  step?: number;
  min?: number;
  max?: number;
  /** Decimal precision. */
  precision?: number;
  /** Called with the numeric value (or null if empty). */
  onChange?: (value: number | null) => void;
  /** Controlled numeric value. */
  value?: number | null;
  defaultValue?: number;
  /** Show increment/decrement buttons. */
  stepper?: boolean;
  /** Show +/- prefix buttons. */
  controls?: boolean;
}

export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(function NumberInput(
  {
    label,
    helperText,
    error,
    size = 'md',
    fullWidth = false,
    required = false,
    step = 1,
    min,
    max,
    precision,
    onChange,
    value: controlledValue,
    defaultValue,
    stepper = true,
    controls = false,
    className = '',
    id,
    disabled,
    ...props
  },
  ref,
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const hasError = Boolean(error);

  const [internal, setInternal] = useState<string>(
    controlledValue != null ? String(controlledValue) :
    defaultValue != null ? String(defaultValue) : '',
  );

  const display = controlledValue != null ? String(controlledValue) : internal;

  function clamp(v: number) {
    if (min != null && v < min) return min;
    if (max != null && v > max) return max;
    return v;
  }

  function format(v: number) {
    return precision != null ? Number(v.toFixed(precision)) : v;
  }

  function increment() {
    const current = parseFloat(display) || 0;
    const next = format(clamp(current + step));
    setInternal(String(next));
    onChange?.(next);
  }

  function decrement() {
    const current = parseFloat(display) || 0;
    const next = format(clamp(current - step));
    setInternal(String(next));
    onChange?.(next);
  }

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    const raw = e.target.value;
    setInternal(raw);
    const parsed = raw === '' ? null : parseFloat(raw);
    if (parsed === null || !isNaN(parsed)) {
      onChange?.(parsed != null ? format(clamp(parsed)) : null);
    }
  }

  return (
    <div className={cls('av-number-input', fullWidth && 'av-number-input-full', hasError && 'av-number-input-error', className)}>
      {label && (
        <label htmlFor={inputId} className="av-form-label">
          {label}{required && <span className="av-form-required" aria-hidden="true"> *</span>}
        </label>
      )}
      <div className={cls('av-number-input-control', size !== 'md' && `av-number-input-${size}`)}>
        {controls && (
          <button type="button" className="av-number-input-btn" onClick={decrement} disabled={disabled || (min != null && parseFloat(display) <= min)} aria-label="Decrease">−</button>
        )}
        <input
          ref={ref}
          id={inputId}
          type="number"
          className={cls('av-input', 'av-number-input-field', size !== 'md' && `av-input-${size}`, hasError && 'av-input-error')}
          value={display}
          step={step}
          min={min}
          max={max}
          required={required}
          disabled={disabled}
          aria-invalid={hasError || undefined}
          onChange={handleChange}
          {...props}
        />
        {controls && (
          <button type="button" className="av-number-input-btn" onClick={increment} disabled={disabled || (max != null && parseFloat(display) >= max)} aria-label="Increase">+</button>
        )}
        {stepper && !controls && (
          <div className="av-number-input-stepper">
            <button type="button" className="av-number-input-step-up" onClick={increment} disabled={disabled || (max != null && parseFloat(display) >= max)} aria-label="Increase" tabIndex={-1}>▲</button>
            <button type="button" className="av-number-input-step-down" onClick={decrement} disabled={disabled || (min != null && parseFloat(display) <= min)} aria-label="Decrease" tabIndex={-1}>▼</button>
          </div>
        )}
      </div>
      {hasError ? (
        <p className="av-form-helper av-form-helper-error" role="alert">{error}</p>
      ) : helperText ? (
        <p className="av-form-helper">{helperText}</p>
      ) : null}
    </div>
  );
});
NumberInput.displayName = 'NumberInput';

// packages/vue/src/NumberInput.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { cls, type Size } from './types';

const props = withDefaults(defineProps<{
  modelValue?: number | null;
  label?: string;
  helperText?: string;
  error?: string;
  size?: Size;
  fullWidth?: boolean;
  step?: number;
  min?: number;
  max?: number;
  precision?: number;
  stepper?: boolean;
  controls?: boolean;
  disabled?: boolean;
  required?: boolean;
  id?: string;
}>(), {
  size: 'md',
  fullWidth: false,
  step: 1,
  stepper: true,
  controls: false,
  required: false,
  disabled: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: number | null];
  'change': [value: number | null];
}>();

const uid = computed(() => props.id ?? `num-${Math.random().toString(36).slice(2, 7)}`);
const hasError = computed(() => Boolean(props.error));

const internal = ref<string>(
  props.modelValue != null ? String(props.modelValue) : ''
);

watch(() => props.modelValue, (newVal) => {
  if (newVal != null) {
    internal.value = String(newVal);
  } else {
    internal.value = '';
  }
});

function clamp(v: number) {
  if (props.min != null && v < props.min) return props.min;
  if (props.max != null && v > props.max) return props.max;
  return v;
}

function format(v: number) {
  return props.precision != null ? Number(v.toFixed(props.precision)) : v;
}

function increment() {
  const current = parseFloat(internal.value) || 0;
  const next = format(clamp(current + props.step));
  internal.value = String(next);
  emit('update:modelValue', next);
  emit('change', next);
}

function decrement() {
  const current = parseFloat(internal.value) || 0;
  const next = format(clamp(current - props.step));
  internal.value = String(next);
  emit('update:modelValue', next);
  emit('change', next);
}

function handleChange(e: Event) {
  const raw = (e.target as HTMLInputElement).value;
  internal.value = raw;
  const parsed = raw === '' ? null : parseFloat(raw);
  if (parsed === null) {
    emit('update:modelValue', null);
    emit('change', null);
  } else if (!isNaN(parsed)) {
    const next = format(clamp(parsed));
    emit('update:modelValue', next);
    emit('change', next);
  }
}
</script>

<template>
  <div :class="cls('av-number-input', fullWidth && 'av-number-input-full', hasError && 'av-number-input-error')">
    <label v-if="label" :for="uid" class="av-form-label">
      {{ label }}
      <span v-if="required" class="av-form-required" aria-hidden="true"> *</span>
    </label>
    
    <div :class="cls('av-number-input-control', size !== 'md' && `av-number-input-${size}`)">
      <button
        v-if="controls"
        type="button"
        class="av-number-input-btn"
        :disabled="disabled || (min != null && parseFloat(internal) <= min)"
        aria-label="Decrease"
        @click="decrement"
      >
        −
      </button>
      
      <input
        type="number"
        :id="uid"
        :class="cls('av-input', 'av-number-input-field', size !== 'md' && `av-input-${size}`, hasError && 'av-input-error')"
        :value="internal"
        :step="step"
        :min="min"
        :max="max"
        :required="required"
        :disabled="disabled"
        :aria-invalid="hasError || undefined"
        @input="handleChange"
      />
      
      <button
        v-if="controls"
        type="button"
        class="av-number-input-btn"
        :disabled="disabled || (max != null && parseFloat(internal) >= max)"
        aria-label="Increase"
        @click="increment"
      >
        +
      </button>
      
      <div v-if="stepper && !controls" class="av-number-input-stepper">
        <button
          type="button"
          class="av-number-input-step-up"
          :disabled="disabled || (max != null && parseFloat(internal) >= max)"
          aria-label="Increase"
          tabindex="-1"
          @click="increment"
        >
          ▲
        </button>
        <button
          type="button"
          class="av-number-input-step-down"
          :disabled="disabled || (min != null && parseFloat(internal) <= min)"
          aria-label="Decrease"
          tabindex="-1"
          @click="decrement"
        >
          ▼
        </button>
      </div>
    </div>
    
    <p v-if="hasError" class="av-form-helper av-form-helper-error" role="alert">
      {{ error }}
    </p>
    <p v-else-if="helperText" class="av-form-helper">
      {{ helperText }}
    </p>
  </div>
</template>
