// packages/react/src/Rating.tsx
import { useState, type HTMLAttributes } from 'react';
import { cls, type Size } from './types';

export interface RatingProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  /** Current value (1–max). */
  value?: number;
  /** Default value (uncontrolled). */
  defaultValue?: number;
  /** Max stars. Defaults to 5. */
  max?: number;
  /** Called when value changes. */
  onChange?: (value: number) => void;
  /** Read-only display. */
  readOnly?: boolean;
  /** Disable interaction. */
  disabled?: boolean;
  /** Size modifier. Defaults to `'md'`. */
  size?: Size;
  /** Custom icon (filled). */
  filledIcon?: string;
  /** Custom icon (empty). */
  emptyIcon?: string;
  /** Accessible label. */
  label?: string;
}

export function Rating({
  value: controlledValue,
  defaultValue = 0,
  max = 5,
  onChange,
  readOnly = false,
  disabled = false,
  size = 'md',
  filledIcon = '★',
  emptyIcon = '☆',
  label = 'Rating',
  className = '',
  ...props
}: RatingProps) {
  const [internal, setInternal] = useState(defaultValue);
  const [hovered, setHovered] = useState(0);
  const current = controlledValue ?? internal;
  const display = hovered || current;

  function handleClick(v: number) {
    if (readOnly || disabled) return;
    setInternal(v);
    onChange?.(v);
  }

  return (
    <div
      className={cls(
        'av-rating',
        size !== 'md' && `av-rating-${size}`,
        readOnly && 'av-rating-readonly',
        disabled && 'av-rating-disabled',
        className,
      )}
      role="radiogroup"
      aria-label={label}
      {...props}
    >
      {Array.from({ length: max }, (_, i) => {
        const v = i + 1;
        const filled = v <= display;
        return (
          <button
            key={v}
            type="button"
            role="radio"
            aria-checked={v === current}
            aria-label={`${v} star${v !== 1 ? 's' : ''}`}
            className={cls('av-rating-star', filled && 'av-rating-star-filled')}
            onClick={() => handleClick(v)}
            onMouseEnter={() => !readOnly && !disabled && setHovered(v)}
            onMouseLeave={() => setHovered(0)}
            disabled={disabled}
            tabIndex={disabled || readOnly ? -1 : 0}
          >
            {filled ? filledIcon : emptyIcon}
          </button>
        );
      })}
    </div>
  );
}

// packages/vue/src/Rating.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { cls, type Size } from './types';

const props = withDefaults(defineProps<{
  modelValue?: number;
  max?: number;
  readOnly?: boolean;
  disabled?: boolean;
  size?: Size;
  filledIcon?: string;
  emptyIcon?: string;
  label?: string;
}>(), {
  modelValue: 0,
  max: 5,
  readOnly: false,
  disabled: false,
  size: 'md',
  filledIcon: '★',
  emptyIcon: '☆',
  label: 'Rating',
});

const emit = defineEmits<{
  'update:modelValue': [value: number];
  'change': [value: number];
}>();

const hoverValue = ref(0);
const displayValue = computed(() => hoverValue.value || props.modelValue);

const className = computed(() =>
  cls(
    'av-rating',
    props.size !== 'md' && `av-rating-${props.size}`,
    props.readOnly && 'av-rating-readonly',
    props.disabled && 'av-rating-disabled'
  )
);

const handleClick = (v: number) => {
  if (props.readOnly || props.disabled) return;
  emit('update:modelValue', v);
  emit('change', v);
};

const handleMouseEnter = (v: number) => {
  if (props.readOnly || props.disabled) return;
  hoverValue.value = v;
};

const handleMouseLeave = () => {
  hoverValue.value = 0;
};
</script>

<template>
  <div
    :class="className"
    role="radiogroup"
    :aria-label="label"
  >
    <button
      v-for="v in max"
      :key="v"
      type="button"
      role="radio"
      :aria-checked="v === modelValue"
      :aria-label="`${v} star${v !== 1 ? 's' : ''}`"
      :class="cls('av-rating-star', v <= displayValue && 'av-rating-star-filled')"
      :disabled="disabled"
      :tabindex="disabled || readOnly ? -1 : 0"
      @click="handleClick(v)"
      @mouseenter="handleMouseEnter(v)"
      @mouseleave="handleMouseLeave"
    >
      {{ v <= displayValue ? filledIcon : emptyIcon }}
    </button>
  </div>
</template>
