// packages/react/src/Skeleton.tsx
import type { HTMLAttributes } from 'react';
import { cls } from './types';

export type SkeletonVariant = 'text' | 'rect' | 'circle' | 'button' | 'avatar' | 'card';

export interface SkeletonProps extends HTMLAttributes<HTMLDivElement> {
  /** Shape preset. Defaults to `'text'`. */
  variant?: SkeletonVariant;
  /** Width (CSS value or number in px). */
  width?: string | number;
  /** Height (CSS value or number in px). */
  height?: string | number;
  /** Number of repeated skeleton lines. */
  lines?: number;
  /** Animation type. Defaults to `'pulse'`. */
  animation?: 'pulse' | 'wave' | 'none';
}

function px(v: string | number) {
  return typeof v === 'number' ? `${v}px` : v;
}

export function Skeleton({
  variant = 'text',
  width,
  height,
  lines,
  animation = 'pulse',
  className = '',
  style,
  ...props
}: SkeletonProps) {
  const computed = cls(
    'av-skeleton',
    `av-skeleton-${variant}`,
    animation !== 'none' && `av-skeleton-${animation}`,
    className,
  );

  const inlineStyle = {
    ...(width ? { width: px(width) } : {}),
    ...(height ? { height: px(height) } : {}),
    ...style,
  };

  if (lines && lines > 1) {
    return (
      <div className="av-skeleton-group" {...props}>
        {Array.from({ length: lines }, (_, i) => (
          <div
            key={i}
            className={computed}
            style={i === lines - 1 ? { ...inlineStyle, width: '70%' } : inlineStyle}
          />
        ))}
      </div>
    );
  }

  return <div className={computed} style={inlineStyle} {...props} />;
}

// packages/vue/src/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls } from './types';

type SkeletonVariant = 'text' | 'rect' | 'circle' | 'button' | 'avatar' | 'card';

const props = withDefaults(defineProps<{
  variant?: SkeletonVariant;
  width?: string | number;
  height?: string | number;
  lines?: number;
  animation?: 'pulse' | 'wave' | 'none';
}>(), { variant: 'text', animation: 'pulse' });

function px(v: string | number) { return typeof v === 'number' ? `${v}px` : v; }

const className = computed(() =>
  cls('av-skeleton', `av-skeleton-${props.variant}`, props.animation !== 'none' && `av-skeleton-${props.animation}`)
);

const inlineStyle = computed(() => ({
  ...(props.width ? { width: px(props.width) } : {}),
  ...(props.height ? { height: px(props.height) } : {}),
}));
</script>

<template>
  <div v-if="lines && lines > 1" class="av-skeleton-group">
    <div
      v-for="i in lines"
      :key="i"
      :class="className"
      :style="i === lines ? { ...inlineStyle, width: '70%' } : inlineStyle"
    />
  </div>
  <div v-else :class="className" :style="inlineStyle" />
</template>
