// packages/react/src/Switch.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { cls, type ColorScheme, type Size } from './types';

export interface SwitchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label?: string;
  /** Color variant when checked. Defaults to `'primary'`. */
  color?: ColorScheme;
  /** Size modifier. Defaults to `'md'`. */
  size?: Size;
  labelPlacement?: 'left' | 'right';
  /** Error state. */
  error?: boolean;
  /** Helper text. */
  helperText?: string;
}

export const Switch = forwardRef<HTMLInputElement, SwitchProps>(function Switch(
  {
    label,
    color = 'primary',
    size = 'md',
    labelPlacement = 'right',
    error = false,
    helperText,
    className = '',
    id,
    disabled,
    ...props
  },
  ref,
) {
  const switchEl = (
    <label
      className={cls(
        'av-switch',
        `av-switch-${color}`,
        size !== 'md' && `av-switch-${size}`,
        error && 'av-switch-error',
        disabled && 'av-switch-disabled',
      )}
      htmlFor={id}
    >
      <input
        ref={ref}
        type="checkbox"
        role="switch"
        id={id}
        className="av-switch-input"
        aria-invalid={error || undefined}
        disabled={disabled}
        {...props}
      />
      <span className="av-switch-track" aria-hidden="true">
        <span className="av-switch-thumb" />
      </span>
    </label>
  );

  return (
    <div className={cls('av-switch-field', error && 'av-switch-field-error', className)}>
      <div className={cls('av-switch-wrapper', `av-switch-label-${labelPlacement}`)}>
        {label && labelPlacement === 'left' && (
          <span className={cls('av-switch-label-text', disabled && 'av-switch-label-disabled')}>{label}</span>
        )}
        {switchEl}
        {label && labelPlacement === 'right' && (
          <span className={cls('av-switch-label-text', disabled && 'av-switch-label-disabled')}>{label}</span>
        )}
      </div>
      {helperText && (
        <p className={cls('av-form-helper', error && 'av-form-helper-error')}>{helperText}</p>
      )}
    </div>
  );
});
Switch.displayName = 'Switch';

// packages/vue/src/Switch.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cls, type ColorScheme, type Size } from './types';

const props = withDefaults(defineProps<{
  modelValue?: boolean;
  label?: string;
  color?: ColorScheme;
  size?: Size;
  labelPlacement?: 'left' | 'right';
  disabled?: boolean;
  id?: string;
}>(), { color: 'primary', size: 'md', labelPlacement: 'right', disabled: false });

const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

const switchClass = computed(() =>
  cls('av-switch', `av-switch-${props.color}`, props.size !== 'md' && `av-switch-${props.size}`)
);
</script>

<template>
  <div :class="cls('av-switch-wrapper', `av-switch-label-${labelPlacement}`)">
    <span v-if="label && labelPlacement === 'left'" class="av-switch-label-text">{{ label }}</span>
    <label :class="switchClass" :for="id">
      <input
        type="checkbox"
        role="switch"
        :id="id"
        class="av-switch-input"
        :checked="modelValue"
        :disabled="disabled"
        @change="emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
      />
      <span class="av-switch-track" aria-hidden="true">
        <span class="av-switch-thumb" />
      </span>
    </label>
    <span v-if="label && labelPlacement === 'right'" class="av-switch-label-text">{{ label }}</span>
  </div>
</template>
