// packages/react/src/ToggleButton.tsx
import { useState, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { cls, type Size, type ColorScheme } from './types';

export interface ToggleButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  /** Current pressed state. */
  selected?: boolean;
  /** Called on toggle. */
  onChange?: (selected: boolean) => void;
  /** Value identifier (used in ToggleButtonGroup). */
  value?: string;
  /** Color when selected. Defaults to `'primary'`. */
  color?: ColorScheme;
  /** Size modifier. Defaults to `'md'`. */
  size?: Size;
}

export function ToggleButton({
  selected,
  onChange,
  value,
  color = 'primary',
  size = 'md',
  className = '',
  children,
  ...props
}: ToggleButtonProps) {
  const [internalSelected, setInternal] = useState(false);
  const isSelected = selected ?? internalSelected;

  function handleClick() {
    const next = !isSelected;
    setInternal(next);
    onChange?.(next);
  }

  return (
    <button
      type="button"
      role="button"
      aria-pressed={isSelected}
      data-value={value}
      className={cls(
        'av-toggle-btn',
        isSelected && `av-toggle-btn-active av-toggle-btn-${color}`,
        size !== 'md' && `av-toggle-btn-${size}`,
        className,
      )}
      onClick={handleClick}
      {...props}
    >
      {children}
    </button>
  );
}

export interface ToggleButtonGroupProps {
  /** Selected values (controlled). */
  value?: string[];
  /** Default selected values (uncontrolled). */
  defaultValue?: string[];
  /** Called with new selection array. */
  onChange?: (values: string[]) => void;
  /** Allow only one selected at a time. */
  exclusive?: boolean;
  /** Size for all buttons. */
  size?: Size;
  /** Color for selected buttons. */
  color?: ColorScheme;
  className?: string;
  children: ReactNode;
}

export function ToggleButtonGroup({
  value: controlledValue,
  defaultValue = [],
  onChange,
  exclusive = false,
  size,
  color = 'primary',
  className = '',
  children,
}: ToggleButtonGroupProps) {
  const [internal, setInternal] = useState<string[]>(defaultValue);
  const selected = controlledValue ?? internal;

  function handleChange(val: string, pressed: boolean) {
    let next: string[];
    if (exclusive) {
      next = pressed ? [val] : [];
    } else {
      next = pressed ? [...selected, val] : selected.filter((v) => v !== val);
    }
    setInternal(next);
    onChange?.(next);
  }

  return (
    <div
      role="group"
      className={cls('av-toggle-btn-group', size && `av-toggle-btn-group-${size}`, className)}
    >
      {/* Clone children injecting selected state */}
      {Array.isArray(children)
        ? (children as React.ReactElement<ToggleButtonProps>[]).map((child) => {
            if (!child?.props?.value) return child;
            return {
              ...child,
              props: {
                ...child.props,
                color,
                size: size ?? child.props.size,
                selected: selected.includes(child.props.value!),
                onChange: (pressed: boolean) => handleChange(child.props.value!, pressed),
              },
            };
          })
        : children}
    </div>
  );
}

import type React from 'react';

// packages/vue/src/ToggleButton.vue
<script setup lang="ts">
import { inject, computed } from 'vue';
import { cls, type Size, type ColorScheme } from './types';

const props = withDefaults(defineProps<{
  selected?: boolean;
  value?: string;
  color?: ColorScheme;
  size?: Size;
}>(), {
  color: 'primary',
  size: 'md',
});

const emit = defineEmits<{
  'update:selected': [value: boolean];
  'change': [value: boolean];
}>();

const groupContext = inject<any>('toggle-button-group', null);

const isSelected = computed(() => {
  if (groupContext && props.value !== undefined) {
    return groupContext.selected.value.includes(props.value);
  }
  return props.selected;
});

const buttonSize = computed(() => (groupContext?.size.value ?? props.size));
const buttonColor = computed(() => (groupContext?.color.value ?? props.color));

const handleClick = () => {
  const next = !isSelected.value;
  emit('update:selected', next);
  emit('change', next);
  
  if (groupContext && props.value !== undefined) {
    groupContext.onChange(props.value, next);
  }
};

const className = computed(() =>
  cls(
    'av-toggle-btn',
    isSelected.value && `av-toggle-btn-active av-toggle-btn-${buttonColor.value}`,
    buttonSize.value !== 'md' && `av-toggle-btn-${buttonSize.value}`
  )
);
</script>

<template>
  <button
    type="button"
    role="button"
    :aria-pressed="isSelected"
    :data-value="value"
    :class="className"
    @click="handleClick"
  >
    <slot />
  </button>
</template>
